import fs from 'node:fs';
import path from 'node:path';
import { parse, stringify } from 'yaml';
import type {
  DocConvertConfig,
  PipelineStep,
  RunContext,
  Ruleset,
  StepConfigAction,
  StepDisposition,
} from '../engine/types.js';
import { CliError } from '../cli/errors.js';
import { CONFIG_FILENAME, CONFIG_VERSION, REQUIRED_STEP_ID } from './constants.js';

export type { DocConvertConfig, StepConfigAction } from '../engine/types.js';

const CONFIG_HEADER = `# doc-convert configuration (generated by \`doc-convert configure\`)
#
# Pandoc import (${REQUIRED_STEP_ID}) always runs and is not listed here.
# Steps with \`run\` execute on conversion in this directory.
# Set a step to \`skip\` to disable it without removing the line.
# Remove a step key entirely to skip it as well.
#
`;

export function configPathForCwd(cwd: string = process.cwd()): string {
  return path.join(cwd, CONFIG_FILENAME);
}

export function findConfigFile(cwd: string = process.cwd()): string | null {
  const p = configPathForCwd(cwd);
  return fs.existsSync(p) ? p : null;
}

export function configurableSteps(ruleset: Ruleset): PipelineStep[] {
  return ruleset.steps.filter((s) => s.id !== REQUIRED_STEP_ID);
}

export function defaultDocConvertConfig(ruleset: Ruleset): DocConvertConfig {
  const steps: Record<string, StepConfigAction> = {};
  for (const step of configurableSteps(ruleset)) {
    steps[step.id] = 'run';
  }
  return { version: CONFIG_VERSION, steps };
}

export function serializeDocConvertConfig(config: DocConvertConfig): string {
  const body = stringify(
    { version: config.version, steps: config.steps },
    { lineWidth: 0 },
  ).trimEnd();
  return `${CONFIG_HEADER}\n${body}\n`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function parseStepActions(
  raw: unknown,
  knownIds: ReadonlySet<string>,
): Record<string, StepConfigAction> {
  if (!isRecord(raw)) {
    throw new CliError(`${CONFIG_FILENAME}: "steps" must be a mapping of step id to run|skip`);
  }

  const steps: Record<string, StepConfigAction> = {};
  for (const [id, value] of Object.entries(raw)) {
    if (id === REQUIRED_STEP_ID) {
      throw new CliError(
        `${CONFIG_FILENAME}: "${REQUIRED_STEP_ID}" cannot be configured (it always runs)`,
      );
    }
    if (value !== 'run' && value !== 'skip') {
      throw new CliError(
        `${CONFIG_FILENAME}: step "${id}" must be "run" or "skip" (got ${JSON.stringify(value)})`,
      );
    }
    if (!knownIds.has(id)) {
      console.warn(`warning: ${CONFIG_FILENAME}: unknown step "${id}" (ignored)`);
      continue;
    }
    steps[id] = value;
  }
  return steps;
}

export function loadDocConvertConfig(
  cwd: string,
  ruleset: Ruleset,
): DocConvertConfig | null {
  const configPath = findConfigFile(cwd);
  if (!configPath) return null;

  let parsed: unknown;
  try {
    parsed = parse(fs.readFileSync(configPath, 'utf8'));
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    throw new CliError(`Failed to parse ${CONFIG_FILENAME}: ${detail}`);
  }

  if (!isRecord(parsed)) {
    throw new CliError(`${CONFIG_FILENAME}: root must be a mapping`);
  }

  const version = parsed.version;
  if (version !== undefined && version !== CONFIG_VERSION) {
    console.warn(
      `warning: ${CONFIG_FILENAME}: version ${String(version)} differs from supported ${CONFIG_VERSION}`,
    );
  }

  const knownIds = new Set(configurableSteps(ruleset).map((s) => s.id));
  const steps = parseStepActions(parsed.steps, knownIds);

  return {
    version: typeof version === 'number' ? version : CONFIG_VERSION,
    steps,
  };
}

/** When no config file exists, all configurable steps are enabled. */
export function isStepEnabledInConfig(
  config: DocConvertConfig | null | undefined,
  stepId: string,
): boolean {
  if (stepId === REQUIRED_STEP_ID) return true;
  if (!config) return true;
  return config.steps[stepId] === 'run';
}

export function plannedStepDisposition(
  step: PipelineStep,
  ctx: RunContext,
  config: DocConvertConfig | null | undefined,
): StepDisposition {
  if (!isStepEnabledInConfig(config, step.id)) {
    return 'skip';
  }
  return step.when ? step.when(ctx) : 'run';
}

export function writeDocConvertConfig(
  cwd: string,
  ruleset: Ruleset,
  options: { force?: boolean } = {},
): string {
  const outPath = configPathForCwd(cwd);
  if (fs.existsSync(outPath) && !options.force) {
    throw new CliError(
      `${CONFIG_FILENAME} already exists at ${outPath} (use --force to overwrite)`,
    );
  }
  const config = defaultDocConvertConfig(ruleset);
  fs.writeFileSync(outPath, serializeDocConvertConfig(config), 'utf8');
  return outPath;
}
